root: true
env:
  node: true
  browser: true
  amd: true
parser: 'vue-eslint-parser'
extends: 
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
parserOptions:
  parser: 'babel-eslint'
  ecmaFeatures:
    legacyDecorators: true
  ecmaVersion: 2018
  sourceType: 'module'
rules:
  indent: "off" #缩进风格
  no-console: "off"
  no-unused-vars: "off"
  # comma-spacing: ['error', {'before': false, 'after': true }]
  linebreak-style: [0, 'error', "windows"]
  semi-style: ['error','last']
  multiline-ternary: 'off'
  vue/no-v-html: "off"
  vue/html-quotes: "off"
  vue/html-self-closing: 'off'
  vue/max-attributes-per-line: 'off'
  vue/require-valid-default-prop: "off"
  vue/require-prop-type-constructor: "off"
  vue/mustache-interpolation-spacing: "off"
  vue/html-closing-bracket-spacing: "off"
  vue/attribute-hyphenation: 'off'
  vue/order-in-components: 'off'
  vue/attributes-order: 'off'